// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"gitlab.com/voice-keyboard/backend-go/pkg"
	"gitlab.com/voice-keyboard/backend-go/pkg/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeConfig(configPath string) (*pkg.Config, error) {
	config, err := pkg.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	return config, nil
}

func InitializeLogger(logLevel logger.LogLevel) logger.Logger {
	loggerLogger := logger.NewLogger(logLevel)
	return loggerLogger
}

func InitializeDatabase(cfg *pkg.Config) (*gorm.DB, error) {
	db, err := pkg.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitializeContainer(configPath string) (*pkg.Container, error) {
	config, err := InitializeConfig(configPath)
	if err != nil {
		return nil, err
	}
	logLevel := ProvideLogLevel(config)
	loggerLogger := InitializeLogger(logLevel)
	db, err := InitializeDatabase(config)
	if err != nil {
		return nil, err
	}
	container := &pkg.Container{
		Config: config,
		Logger: loggerLogger,
		DB:     db,
	}
	return container, nil
}

// wire.go:

func ProvideLogLevel(cfg *pkg.Config) logger.LogLevel {
	if cfg.App.Debug {
		return "debug"
	}
	return "info"
}
