// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gitlab.com/voice-keyboard/backend-go/internal/interfaces"
	"gitlab.com/voice-keyboard/backend-go/internal/services"
	"gitlab.com/voice-keyboard/backend-go/pkg"
	"gitlab.com/voice-keyboard/backend-go/pkg/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeConfig(configPath string) (*pkg.Config, error) {
	config, err := pkg.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	return config, nil
}

func InitializeLogger(logLevel logger.LogLevel) logger.Logger {
	loggerLogger := logger.NewLogger(logLevel)
	return loggerLogger
}

func InitializeDatabase(cfg *pkg.Config) (*gorm.DB, error) {
	db, err := pkg.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitializeValidator() (*validator.Validate, error) {
	validate, err := pkg.NewValidator()
	if err != nil {
		return nil, err
	}
	return validate, nil
}

func InitializeEmailer(cfg *pkg.Config, logger2 logger.Logger) (*pkg.Emailer, error) {
	emailer := pkg.NewEmailer(cfg, logger2)
	return emailer, nil
}

func InitializeAPIErrorHandler(logger2 logger.Logger) (*pkg.APIErrorHandler, error) {
	apiErrorHandler := pkg.NewAPIErrorHandler(logger2)
	return apiErrorHandler, nil
}

func InitializeContainer(configPath string) (*pkg.Container, error) {
	config, err := InitializeConfig(configPath)
	if err != nil {
		return nil, err
	}
	logLevel := ProvideLogLevel(config)
	loggerLogger := InitializeLogger(logLevel)
	db, err := InitializeDatabase(config)
	if err != nil {
		return nil, err
	}
	emailer, err := InitializeEmailer(config, loggerLogger)
	if err != nil {
		return nil, err
	}
	validate, err := InitializeValidator()
	if err != nil {
		return nil, err
	}
	apiErrorHandler, err := InitializeAPIErrorHandler(loggerLogger)
	if err != nil {
		return nil, err
	}
	yandexOAuthService := services.NewYandexOAuthService(config, loggerLogger)
	authService := services.NewAuthService(db, config, loggerLogger, emailer, yandexOAuthService)
	audioService := services.NewAudioService(loggerLogger)
	container := &pkg.Container{
		Config:             config,
		Logger:             loggerLogger,
		DB:                 db,
		Emailer:            emailer,
		Validator:          validate,
		ErrorHandler:       apiErrorHandler,
		AuthService:        authService,
		YandexOAuthService: yandexOAuthService,
		AudioService:       audioService,
	}
	return container, nil
}

// wire.go:

func ProvideLogLevel(cfg *pkg.Config) logger.LogLevel {
	if cfg.App.Debug {
		return "debug"
	}
	return "info"
}

var ServiceSet = wire.NewSet(services.NewYandexOAuthService, wire.Bind(new(interfaces.YandexOAuthServiceInterface), new(*services.YandexOAuthService)), services.NewAuthService, wire.Bind(new(interfaces.AuthServiceInterface), new(*services.AuthService)), services.NewAudioService, wire.Bind(new(interfaces.AudioServiceInterface), new(*services.AudioService)))
