include:
  - local: .gitlab-ci.common.yml

variables:
  PROJECT: voice-keyboard/backend
  REGISTRY: $REGISTRY_HOST/$PROJECT
  IMAGE_NAME: $REGISTRY/app

stages:
  - build
  - deploy

app:
  stage: build
  extends:
    - .job-build
  script:
    - !reference [.job-build, script]
  when: manual

# Deploy job template
.deploy:
  stage: deploy
  needs:
    - app
  variables:
    SSH_USER: !reference [.ssh-auth, variables, SSH_USER]
    NETWORK_NAME: traefik
    CONTAINER_NAME: backend
    CONFIG_FILE: /opt/app/config.yml
    RELEASE_DIR: /opt/app/releases
  before_script:
    - !reference [.ssh-auth, before_script]
  script:
    - echo "Deploying application to $IP"

    # Copy config files
    # - echo "$CONFIG_VARIABLES" | base64 -d > config.yml && scp config.yml $SSH_USER@$IP:"$CONFIG_FILE" && rm config.yml

    # Login to GitLab registry
    - ssh $SSH_USER@$IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"

    # Restart containers
    - ssh $SSH_USER@$IP "
      docker pull $IMAGE_NAME:$TAG &&
      docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:current &&
      docker rm -f $CONTAINER_NAME > /dev/null 2>&1 || true &&
      cd /opt/app && docker compose down && docker compose up -d
      "
      # docker run -d
      # --restart=always
      # --name=$CONTAINER_NAME
      # --network=$NETWORK_NAME
      # -v $CONFIG_FILE:/app/config.yml:ro
      # -v $RELEASE_DIR:/app/releases
      # $IMAGE_NAME:$TAG

    # Run migrations
    - ssh $SSH_USER@$IP "docker exec $CONTAINER_NAME /app/voice-key database:migrations:migrate"
  allow_failure: false

production:
  environment:
    name: production
    url: https://example.com
  variables:
    IP: "$DEPLOY_HOST"
    SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY_PRODUCTION"
  extends: .deploy
  when: manual
  # only:
  # - tags
