name: voice-key-backend-go-prod

services:
  # Database service
  db:
    container_name: voice-key-db
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./.docker/volumes/postgresql-prod:/var/lib/postgresql/data/pgdata
      - ./.docker/volumes/pg-backups-prod:/backups
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Application service
  spichki:
    container_name: spichki-backend
    image: registry.gitlab.com/voice-keyboard/backend/app:current
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /home/ops/services/voice-key/config.yml:/app/config.yml:ro
      - /home/ops/services/voice-key/releases:/app/releases
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.spichki.rule=Host(`b.spichki.app`)
      - traefik.http.routers.spichki.entrypoints=web,websecure
      - traefik.http.routers.spichki.tls=true
      - traefik.http.routers.spichki.tls.certresolver=production
      - traefik.http.middlewares.spichki.headers.SSLRedirect=true
      - traefik.http.middlewares.spichki.headers.STSSeconds=315360000
      - traefik.http.middlewares.spichki.headers.browserXSSFilter=true
      - traefik.http.middlewares.spichki.headers.contentTypeNosniff=true
      - traefik.http.middlewares.spichki.headers.forceSTSHeader=true
      - traefik.http.middlewares.spichki.headers.SSLHost=spichki.app
      - traefik.http.middlewares.spichki.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.spichki.headers.STSPreload=true
      - traefik.http.routers.spichki.middlewares=spichki@docker

networks:
  traefik:
    external: true
