package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func init() {
	registerMigration(&gormigrate.Migration{
		ID: "202403302014_create_users_social_auths",
		Migrate: func(tx *gorm.DB) error {
			// Создаем основную таблицу
			if err := tx.Exec(`
				CREATE TABLE users_social_auths (
					"id" int8 GENERATED BY DEFAULT AS IDENTITY,
					"user_id" int8 NOT NULL,
					"provider" varchar(50) NOT NULL,
					"provider_user_id" varchar(255) NOT NULL,
					"provider_email" varchar(255),
					"provider_data" jsonb,
					"created_at" timestamptz(6) NOT NULL DEFAULT NOW(),
					"updated_at" timestamptz(6) NOT NULL DEFAULT NOW(),
					"deleted_at" timestamptz(6),

					PRIMARY KEY ("id"),
					CONSTRAINT fk_users_social_auths_user FOREIGN KEY (user_id)
						REFERENCES users(id) ON DELETE CASCADE,
					CONSTRAINT ux_provider_user UNIQUE (provider, provider_user_id)
				)
			`).Error; err != nil {
				return err
			}

			// Создаем индекс для поиска по провайдеру
			if err := tx.Exec(`
				CREATE INDEX idx_users_social_auths_provider ON users_social_auths (provider)
			`).Error; err != nil {
				return err
			}

			// Создаем индекс для soft delete
			return tx.Exec(`
				CREATE INDEX idx_users_social_auths_deleted_at ON users_social_auths (deleted_at)
			`).Error
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Exec("DROP TABLE IF EXISTS users_social_auths").Error
		},
	})
}
