package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func init() {
	registerMigration(&gormigrate.Migration{
		ID: "20240330_create_users_table",
		Migrate: func(tx *gorm.DB) error {
			return tx.Exec(`
				CREATE TABLE users (
					"id" int4 GENERATED BY DEFAULT AS IDENTITY,
					"name" varchar(255),
					"created_at" timestamptz(6) NOT NULL DEFAULT NOW(),
					"updated_at" timestamptz(6) NOT NULL DEFAULT NOW(),
					"deleted_at" timestamptz(6),
					PRIMARY KEY ("id"),
					CONSTRAINT ux_users_email UNIQUE (email)
				);

				CREATE INDEX idx_users_deleted_at ON users (deleted_at);
			`).Error
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Exec("DROP TABLE IF EXISTS users").Error
		},
	})
}
