package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func init() {
	registerMigration(&gormigrate.Migration{
		ID: "20240330_create_user_social_auths",
		Migrate: func(tx *gorm.DB) error {
			return tx.Exec(`
				CREATE TABLE user_social_auths (
					"id" int4 GENERATED BY DEFAULT AS IDENTITY,
					"user_id" int4 NOT NULL,
					"provider" varchar(50) NOT NULL,
					"provider_user_id" varchar(255) NOT NULL,
					"provider_email" varchar(255),
					"provider_data" jsonb,
					"created_at" timestamptz(6) NOT NULL DEFAULT NOW(),
					"updated_at" timestamptz(6) NOT NULL DEFAULT NOW(),
					"deleted_at" timestamptz(6),

					PRIMARY KEY ("id"),
					CONSTRAINT fk_user_social_auths_user FOREIGN KEY (user_id)
						REFERENCES users(id) ON DELETE CASCADE,
					CONSTRAINT ux_provider_user UNIQUE (provider, provider_user_id)
				);

				-- Индекс для поиска по провайдеру
				CREATE INDEX idx_user_social_auths_provider ON user_social_auths (provider);

				-- Индекс для soft delete
				CREATE INDEX idx_user_social_auths_deleted_at ON user_social_auths (deleted_at);
			`).Error
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Exec("DROP TABLE IF EXISTS user_social_auths").Error
		},
	})
}
