package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func init() {
	registerMigration(&gormigrate.Migration{
		ID: "202404050040_create_user_tokens_table",
		Migrate: func(tx *gorm.DB) error {
			if err := tx.Exec(`
                CREATE TABLE user_tokens (
                    "id" int8 GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" int8 NOT NULL,
                    "refresh_token" varchar(255) NOT NULL,
                    "created_at" timestamptz(6) NOT NULL DEFAULT NOW(),
                    "expires_at" timestamptz(6) NOT NULL,
                    PRIMARY KEY ("id"),
                    CONSTRAINT fk_user_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
            `).Error; err != nil {
				return err
			}

			// Индекс для поиска по refresh_token
			if err := tx.Exec(`
                CREATE UNIQUE INDEX idx_user_tokens_refresh_token ON user_tokens (refresh_token)
            `).Error; err != nil {
				return err
			}

			// Индекс для поиска по user_id
			return tx.Exec(`
                CREATE INDEX idx_user_tokens_user_id ON user_tokens (user_id)
            `).Error
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Exec("DROP TABLE IF EXISTS user_tokens").Error
		},
	})
}
